[webserver]
54.xxx.xxx.xxx ansible_user=ubuntu #replace dummy ip with your actual ec2 instance public ip ( ip4 )


[db]
3.xxx.xxx.xxx ansible_user=ubuntu #replace dummy ip with your actual ec2 instance public ip ( ip4 )
